version: 0.2
phases:
  pre_build:
    commands:
      - echo "DATABASE_URL=$DATABASE_URL"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 841162688523.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo "DATABASE_URL=$DATABASE_URL" > .env
      - echo "ERP_SYNC_ITEM_PROCESS_JOB_QUEUE_URL=$ERP_SYNC_ITEM_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "LOG_GROUP_NAME=$LOG_GROUP_NAME" >> .env
      - echo "LOG_STREAM_PREFIX=$LOG_STREAM_PREFIX" >> .env
      - echo "ERP_SYNC_ORDER_PROCESS_JOB_QUEUE_URL=$ERP_SYNC_ORDER_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "ERP_INVENTORY_FACTOR=$ERP_INVENTORY_FACTOR" >> .env
      - echo "MKT_SYNC_ITEM_PROCESS_JOB_QUEUE_URL=$MKT_SYNC_ITEM_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "ERP_YUJU_GUIDE_FETCH_JOB_QUEUE_URL=$ERP_YUJU_GUIDE_FETCH_JOB_QUEUE_URL" >> .env
      - echo "NODE_ENV=$NODE_ENV" >> .env
      - echo "API_REST_NEXT_CLOUD_URL=$API_REST_NEXT_CLOUD_URL" >> .env
      - echo "AWS_REGION_SES=$AWS_REGION_SES" >> .env
      - echo "YUJU_API_URL=$YUJU_API_URL" >> .env
      - echo "INVENTORY_FILES=$INVENTORY_FILES" >> .env
      - echo "BUCKET_INVENTORY_FILES=$BUCKET_INVENTORY_FILES" >> .env
      - echo "Building Docker image..."
      - docker build --no-cache -t api-erp-sandbox:latest . -f pipeline-support/erp/Dockerfile.sbx
      - docker tag api-erp-sandbox:latest 841162688523.dkr.ecr.us-west-2.amazonaws.com/api-erp-sandbox:latest
  post_build:
    commands:
      - cat .env
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 841162688523.dkr.ecr.us-west-2.amazonaws.com/api-erp-sandbox:latest
      - echo "Image pushed to ECR."
      - printf '[{"name":"container-erp-api-sandbox","imageUri":"841162688523.dkr.ecr.us-west-2.amazonaws.com/api-erp-sandbox:latest"}]' > imageDetail.json

      - cat imageDetail.json
artifacts:
  files:
    - .env
    - imageDetail.json
