version: 0.2
phases:
  pre_build:
    commands:
      - echo "DATABASE_URL=$DATABASE_URL"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 841162688523.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo "DATABASE_URL=$DATABASE_URL" > .env
      - echo "AMZN_SECRET_ACCESS_KEY=$AMZN_SECRET_ACCESS_KEY" >> .env
      - echo "AMZN_SELLING_PARTNER_APP_CLIENT_SECRET=$AMZN_SELLING_PARTNER_APP_CLIENT_SECRET" >> .env
      - echo "MERL_API_KEY_SECRET=$MERL_API_KEY_SECRET" >> .env
      - echo "FRONTEND_ADMIN_URL=$FRONTEND_ADMIN_URL" >> .env
      - echo "FRONTEND_URL=$FRONTEND_URL" >> .env
      - echo "AWS_ACCESS_KEY_ID_SES=$AWS_ACCESS_KEY_ID_SES" >> .env
      - echo "AWS_SECRET_ACCESS_KEY_SES=$AWS_SECRET_ACCESS_KEY_SES" >> .env
      - echo "SHOPIFY_API_KEY=$SHOPIFY_API_KEY" >> .env
      - echo "SHOPIFY_API_SECRET=$SHOPIFY_API_SECRET" >> .env
      - echo "SHOPIFY_ACCESS_TOKEN=$SHOPIFY_ACCESS_TOKEN" >> .env
      - echo "AMAZON_REFRESH_TOKEN=$AMAZON_REFRESH_TOKEN" >> .env
      - echo "MKT_SYNC_ORDER_PROCESS_JOB_QUEUE_URL=$MKT_SYNC_ORDER_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "MKT_SYNC_ITEM_PROCESS_JOB_QUEUE_URL=$MKT_SYNC_ITEM_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "ERP_SYNC_ITEM_PROCESS_JOB_QUEUE_URL=$ERP_SYNC_ITEM_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "LOG_GROUP_NAME=$LOG_GROUP_NAME" >> .env
      - echo "YUJU_API_URL=$YUJU_API_URL" >> .env
      - echo "NODE_ENV=$NODE_ENV" >> .env
      - echo "JWT_EXPIRES_IN=$JWT_EXPIRES_IN" >> .env
      - echo "API_ERP_URL=$API_ERP_URL" >> .env
      - echo "ERP_INVENTORY_FACTOR=$ERP_INVENTORY_FACTOR" >> .env
      - echo "API_REST_NEXT_CLOUD_URL=$API_REST_NEXT_CLOUD_URL" >> .env
      - echo "ERP_SYNC_ORDER_PROCESS_JOB_QUEUE_URL=$ERP_SYNC_ORDER_PROCESS_JOB_QUEUE_URL" >> .env
      - echo "ERP_YUJU_GUIDE_FETCH_JOB_QUEUE_URL=$ERP_YUJU_GUIDE_FETCH_JOB_QUEUE_URL" >> .env
      - echo "AWS_REGION_SES=$AWS_REGION_SES" >> .env
      - echo "INVENTORY_FILES=$INVENTORY_FILES" >> .env
      - echo "YUJU_QUEUE_URL=$YUJU_QUEUE_URL" >> .env
      - echo "YUJU_APP_CLIENT_ID=$YUJU_APP_CLIENT_ID" >> .env
      - echo "YUJU_APP_SECRET_KEY=$YUJU_APP_SECRET_KEY" >> .env
      - echo "Building Docker image..."
      - docker build --no-cache -t api-f360-sandbox:latest . -f pipeline-support/core/Dockerfile.sbx
      - docker tag api-f360-sandbox:latest 841162688523.dkr.ecr.us-west-2.amazonaws.com/api-f360-sandbox:latest
  post_build:
    commands:
      - cat .env
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 841162688523.dkr.ecr.us-west-2.amazonaws.com/api-f360-sandbox:latest
      - echo "Image pushed to ECR."
      - printf '[{"name":"container-api-sandbox","imageUri":"841162688523.dkr.ecr.us-west-2.amazonaws.com/api-f360-sandbox:latest"}]' > imageDetail.json

      - cat imageDetail.json
artifacts:
  files:
    - .env
    - imageDetail.json
